
# The directory in which the backup files from Signal Android will appear
dir_synced=$1
# The directory in which to put all the backup files for long-term storage
dir_output=$2
# The directory in which to put the html generated by the exporting step
# This will be the webroot you set in the webserver
dir_export=$3
# This is a file containing the password for all the signal backups
password=$(cat "$4")

# The most recent backup file received from Signal Android
most_recent_backup=$(find "$dir_synced" -name 'signal-*.backup' | sort --reverse | head -n 1 -)

# The date extracted from the previously processed file from Signal Android
cutoff_raw=$(cat "$dir_output"/cutoff_raw.txt)
# shellcheck disable=SC2001
cutoff=$(echo "$cutoff_raw" | sed 's#\(....-..-..\)-\(..\)-\(..\)-\(..\)#\1 \2:\3:\4#')

# The date extracted from the currently most recent file from Signal Android
# shellcheck disable=SC2001
cutoff_next_raw=$(echo "$most_recent_backup" | sed 's:.*/signal-\(.*\)\.backup:\1:')
# Convert to RFC 3339 (but missing the timezone)
# shellcheck disable=SC2001
cutoff_next=$(echo "$cutoff_next_raw" | sed 's#\(....-..-..\)-\(..\)-\(..\)-\(..\)#\1 \2:\3:\4#')

# Prepare the paths, initially inside a new directory for easily deleting older versions
cropped=${dir_output}/.next/signal-${cutoff_next_raw}-cropped-since-${cutoff_raw}.backup
cropped_log=${dir_output}/.next/signal-${cutoff_next_raw}-cropped-since-${cutoff_raw}.log
merged=${dir_output}/.next/merged-${cutoff_next_raw}.backup
merged_log=${dir_output}/.next/merged-${cutoff_next_raw}.log
export_log=${dir_output}/.next/export-${cutoff_next_raw}.log

merged_prev=${dir_output}/merged-${cutoff_raw}.backup

if [[ -z "$cutoff_next_raw" ]]; then
  echo "NOTHING TO DO: THERE IS NO LATEST BACKUP"
  exit 0
fi

if [[ "$cutoff_next_raw" == "$cutoff_raw" ]]; then
  echo "NOTHING TO DO: LATEST IS ALREADY PROCESSED, cutoff=$cutoff"
  exit 0
fi

mkdir "$dir_output/.next"

echo "CROPPING"
echo "signalbackup-tools \"$most_recent_backup\" --croptodates \"$cutoff,$cutoff_next\" --output \"$cropped\" > \"$cropped_log\""
signalbackup-tools \
  "$most_recent_backup" "$password" \
  --croptodates "$cutoff,$cutoff_next" \
  --output "$cropped" --opassphrase "$password" \
  > "$cropped_log"

echo "MERGING"
echo "signalbackup-tools \"$merged_prev\" --importthreads ALL --source \"$cropped\" --output \"$merged\" > \"$merged_log\""
signalbackup-tools \
  "$merged_prev" "$password" \
  --importthreads ALL --source "$cropped" --sourcepassphrase "$password" \
  --output "$merged" --opassphrase "$password" \
  > "$merged_log"

echo "EXPORTING"
echo "signalbackup-tools \"$merged\" --allhtmlpages --includereceipts --split 1000 --append --exporthtml \"$dir_export\" > \"$export_log\""
signalbackup-tools \
  "$merged" "$password" \
  --allhtmlpages --includereceipts --split 1000 \
  --append --exporthtml "$dir_export" \
  > "$export_log"

echo "FINISHING"
# Keep one previous merged backup, just in case something went wrong
mv "$merged_prev" "$dir_output/.next"

# Clean up previous backups from output dir
find "$dir_output" -mindepth 1 -maxdepth 1 -type f -delete

# Move some remains into the output dir
# shellcheck disable=SC2046
mv $(find "$dir_output/.next" -mindepth 1 -maxdepth 1 -type f) "$dir_output"
rm -d "$dir_output/.next"

# Put original file from phone in output dir
mv -v "$most_recent_backup" "$dir_output/"

# Remember cutoff
echo "$cutoff_next_raw" > "$dir_output/cutoff_raw.txt"
