
# The directory in which the backup files from Signal Android will appear
dir_synced=$1
# The directory in which to put all the backup files for long-term storage
dir_output=$2
# The directory in which to put the html generated by the exporting step
# This will be the webroot you set in the webserver
dir_export=$3
# This is a file containing the password for all the signal backups
password=$(cat "$4")

# The most recent backup file received from Signal Android
most_recent_backup=$(find "$dir_synced" -name 'signal-*.backup' | sort --reverse | head -n 1 -)

# The date extracted from the previously processed file from Signal Android
cutoff_raw=$(cat "$dir_output"/cutoff_raw.txt)
# shellcheck disable=SC2001
cutoff=$(echo "$cutoff_raw" | sed 's#\(....-..-..\)-\(..\)-\(..\)-\(..\)#\1 \2:\3:\4#')

# The date extracted from the currently most recent file from Signal Android
# shellcheck disable=SC2001
cutoff_next_raw=$(echo "$most_recent_backup" | sed 's:.*/signal-\(.*\)\.backup:\1:')
# Convert to RFC 3339 (but missing the timezone)
# shellcheck disable=SC2001
cutoff_next=$(echo "$cutoff_next_raw" | sed 's#\(....-..-..\)-\(..\)-\(..\)-\(..\)#\1 \2:\3:\4#')

cropped=${dir_output}/signal-${cutoff_next_raw}-cropped-since-${cutoff_raw}.backup
cropped_log=${dir_output}/signal-${cutoff_next_raw}-cropped-since-${cutoff_raw}.log
merged=${dir_output}/merged-${cutoff_next_raw}.backup
merged_log=${dir_output}/merged-${cutoff_next_raw}.log

merged_prev=${dir_output}/merged-${cutoff_raw}.backup

export_log=${dir_output}/export-${cutoff_next_raw}.log

if [[ "$cutoff_next_raw" == "$cutoff_raw" ]]; then
  echo "NOTHING TO DO; CUTOFF IS $cutoff"
  exit 0
fi

echo "CROPPING"
echo "signalbackup-tools \"$most_recent_backup\" --croptodates \"$cutoff,$cutoff_next\" --output \"$cropped\" > \"$cropped_log\""
signalbackup-tools \
  "$most_recent_backup" "$password" \
  --croptodates "$cutoff,$cutoff_next" \
  --output "$cropped" --opassphrase "$password" \
  > "$cropped_log"

echo "MERGING"
echo "signalbackup-tools \"$merged_prev\" --importthreads ALL --source \"$cropped\" --output \"$merged\" > \"$merged_log\""
signalbackup-tools \
  "$merged_prev" "$password" \
  --importthreads ALL --source "$cropped" --sourcepassphrase "$password" \
  --output "$merged" --opassphrase "$password" \
  > "$merged_log"

echo "EXPORTING"
echo "signalbackup-tools \"$merged\" --allhtmlpages --includereceipts --split 1000 --append --exporthtml \"$dir_export\" > \"$export_log\""
signalbackup-tools \
  "$merged" "$password" \
  --allhtmlpages --includereceipts --split 1000 \
  --append --exporthtml "$dir_export" \
  > "$export_log"

echo "FINISHING"
mv -v "$most_recent_backup" "$dir_output/"
echo "$cutoff_next_raw" > "$dir_output/cutoff_raw.txt"
